return {
	require('config.plugin.a'),
	require('config.plugin.ale'),
	require('config.plugin.cmp'),
	require('config.plugin.indent-blankline'),
	require('config.plugin.lspconfig'),
	require('config.plugin.lualine'),
	require('config.plugin.nerdcommenter'),
	require('config.plugin.nvim-cmp'),
	require('config.plugin.nvim-tree'),
	require('config.plugin.symbols-outline'),
	require('config.plugin.tagbar'),
	require('config.plugin.telescope'),
	require('config.plugin.treesitter'),
	require('config.plugin.trouble'),
	require('config.plugin.ultisnips'),
}
