return {
  require "config.plugin.cmp",
  require "config.plugin.comment",
  require "config.plugin.gitsigns",
  require "config.plugin.lspconfig",
  require "config.plugin.lualine",
  require "config.plugin.luasnip",
  require "config.plugin.null-ls",
  require "config.plugin.nvim-tree",
  require "config.plugin.rust-tools",
  require "config.plugin.symbols-outline",
  require "config.plugin.tagbar",
  require "config.plugin.telescope",
  require "config.plugin.treesitter",
}
